version: "3.3"

services:
  nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy
    restart: "on-failure"
    ports:
      - 80:80
    volumes:
      - ./mp-cloudserver/nginx.conf:/etc/nginx/nginx.conf
      - ./mp-client/client/build:/usr/share/nginx/html

  mp-client:
    build:
      context: ./mp-client/client
    container_name: mp-client
    expose:
      - 3000
    volumes:
      - "./mp-client:/mp-client"
      - "/mp-client/node_modules"

  server:
    build:
      context: ./mp-server/server
    container_name: mp-server
    restart: "on-failure"
    expose:
      - 3601
    volumes:
      - "./mp-server:/mp-server"
      - "/mp-server/server/node_modules"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
