version: '3.3'

services:
  web:
    image: nginx:latest
    container_name: web
    restart: "on-failure"
    ports:
      - "80:80"
    volumes:
      - ./mp-cloudserver/client.conf:/etc/nginx/conf.d/client.conf
      - ./mp-cloudserver/server.conf:/etc/nginx/conf.d/server.conf
      - ./mp-client/client/build:/usr/share/nginx/html
      - './mp-server/server:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true