version: '3.3'

services:
  web:
    image: nginx:latest
    container_name: web
    restart: "on-failure"
    ports:
      - "80:80"
    volumes:
      - ./mp-cloudserver/nginx.conf:/etc/nginx/nginx.conf
      - ./mp-client/client/build:/usr/share/nginx/html
  server:
    build:
      context: ./mp-server/server
    container_name: server
    restart: "on-failure"
    ports:
      - "3601:3601"
    volumes:
      - './mp-server/server:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true