version: "3.3"

services:
  nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy
    restart: "on-failure"
    ports:
      - 80:80
    volumes:
      - ./MP-CloudServer/nginx.conf:/etc/nginx/nginx.conf
      - ./MP-Client/build:/usr/share/nginx/html

  MP-Client:
    build:
      context: ./MP-Client/
    container_name: MP-Client
    expose:
      - 3000
    volumes:
      - "./MP-Client:/MP-Client"
      - "/MP-Client/node_modules"

  server:
    build:
      context: ./MP-Server/
    container_name: MP-Server
    restart: "on-failure"
    expose:
      - 8080
    volumes:
      - "./MP-Server:/MP-Server"
      - "/MP-Server/node_modules"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
